//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _5_labka
{
    using System;
    using System.Collections.Generic;
    
    public partial class Returnss
    {
        public int ReturnID { get; set; }
        public int OrderDetailID { get; set; }
        public string ReturnReason { get; set; }
    
        public virtual OrderDetails OrderDetails { get; set; }
    }
}
