//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _5_labka
{
    using System;
    using System.Collections.Generic;
    
    public partial class Servis
    {
        public int ServisID { get; set; }
        public int OrderID { get; set; }
        public string Opisanie { get; set; }
        public int Price { get; set; }
    
        public virtual Orders Orders { get; set; }
    }
}
